### ISSUE TITLE
Issue with firstWeekday. The header is not updating.

### ISSUE THREAD

**Issue by jfbomber** [mmick66/CalendarView#99] opened 2019-11-21 16:48 UTC
For the CalendarView when I set the first day of the week variable to Sunday it is updating the calendar days correctly but not the header at the top.

```
self.calendarView.style.firstWeekday = .sunday
self.calendarView.style.locale = Locale(identifier: "en_US")
```

![Simulator Screen Shot - iPhone 11 - 2019-11-21 at 08 38 04](https://user-images.githubusercontent.com/1092988/69358351-8f991700-0c3b-11ea-9c6c-40a49be2dfa5.png)

**Comment by azeemgujjar** [comment] 2019-12-12 09:11
Hi i am facing the same issue, did you get solution? or fix for this bug?

**Comment by mudassarahmad09** [comment] 2019-12-12 09:16
I'm experiencing the same problem.  @mmick66, do you have any advice for how to solve this issue?

**Comment by mmick66** [comment] 2019-12-12 09:26
I’m going to have a look.

**Comment by azeemgujjar** [comment] 2019-12-12 09:45
> I’m going to have a look.

Awesome, will be thankful if you can fix issue or suggest some hack quickly..

**Comment by jfbomber** [comment] 2019-12-12 17:46
It seems like it had to do with the MomentSwift library. I found some people talk about how they had duplicate days with that.

**Comment by azeemgujjar** [comment] 2019-12-20 07:07
Hi @mmick66  any update with this issue? when are you going to fix this bug

**Comment by mmick66** [comment] 2019-12-20 07:41
Today, I promise!

**Comment by azeemgujjar** [comment] 2019-12-20 08:06
Actually this is very embarrassing i used your library and already demonstrate to client, now can't even remove your library and use native calendar.. and this is around 30 days old issue. and still not fixed.

**Comment by azeemgujjar** [comment] 2019-12-20 08:06
> Today, I promise!

lets see

**Comment by mmick66** [comment] 2019-12-20 08:26
<img width="282" alt="Screenshot 2019-12-20 at 10 25 32" src="https://user-images.githubusercontent.com/342781/71240992-262c2700-2313-11ea-8cc9-5b8306a2d1f6.png">
 Have a look above. I can't really seem to be able to reproduce it. Could it be a version thing? How are you installing it?

**Comment by azeemgujjar** [comment] 2019-12-20 08:36
change header to starting to sunday
then when calendar open first time it will show wrong dates order.

**Comment by mmick66** [comment] 2019-12-20 08:52
<img width="282" alt="Screenshot 2019-12-20 at 10 51 41" src="https://user-images.githubusercontent.com/342781/71242486-c2a3f880-2316-11ea-914a-3aff05f4eafa.png">
This is what I'm seeing...

**Comment by mmick66** [comment] 2019-12-20 10:12
> Actually this is very embarrassing i used your library and already demonstrate to client, now can't even remove your library and use native calendar.. and this is around 30 days old issue. and still not fixed.

I am not suggesting you remove the component! I am asking whether you have the right version. I had merged some pull requests around the time you raised the issue. As you can see from above, I am not able to reproduce it. Can you please check you are on the latest version of the component?

**Comment by azeemgujjar** [comment] 2019-12-20 11:02
KDCalendar 1.8.3 
install by pod

- To produce just change starting day to .Sunday
- when calender first time open it will show selected date to yesterday.
- next time it will work normally.
- to reproduce exit application and repeat

**Comment by azeemgujjar** [comment] 2019-12-20 11:34
> > Actually this is very embarrassing i used your library and already demonstrate to client, now can't even remove your library and use native calendar.. and this is around 30 days old issue. and still not fixed.
> 
> I am not suggesting you remove the component! I am asking whether you have the right version. I had merged some pull requests around the time you raised the issue. As you can see from above, I am not able to reproduce it. Can you please check you are on the latest version of the component?

Ok Thank you so much i am just going to try this

**Comment by mmick66** [comment] 2019-12-20 12:23
Please let me know. I really want to get to the bottom of this.

**Comment by mmick66** [comment] 2019-12-22 17:55
> KDCalendar 1.8.3
> install by pod
> 
> @mmick66
> 
> * To produce just change starting day to .Sunday
> * when calender first time open it will show selected date to yesterday.
> * next time it will work normally.
> * to reproduce exit application and repeat

I cannot seem to reproduce. Could you please zip your project and send it here? I will have a look...

**Comment by azeemgujjar** [comment] 2019-12-26 09:29
Hi @mmick66 , 
I apologize for late response, these days i was actually trying to reproduce that bug on my side but till now its working fine. i was removed previous version of library and use your latest commit.

Thank you so much for follow-up i will keep in touch with you and update you if any issue i found.

**Comment by mmick66** [comment] 2019-12-27 16:02
No problem... I'm glad it got resolved.

**Closed by mmick66** 2019-12-27 16:02 UTC
